-- Migration 0003: import the 50 Supabase tracks (files already copied to R2 via rclone)
-- Paste this whole file into: Cloudflare Dashboard -> Storage & Databases -> D1 -> hedge-music-alpha-db -> Console -> Execute
-- Safe to re-run: INSERT OR IGNORE on unique original_url

-- remove test tracks created during debugging (owner-prefixed paths = test rows; flat paths below = real imports)
DELETE FROM tracks WHERE storage_path LIKE '%/youtube-%.mp3';
DELETE FROM tracks WHERE storage_path LIKE '%/extractor-%.mp3';

INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('26b6ed85-05e2-4390-97ca-d88c64595661','https://www.youtube.com/watch?v=017K5zu2KLg','youtube','017K5zu2KLg','No Disc X Cheb Redouane Rahmini Kima Rabi Yerham [Weld Khali] Remix 2026','NO DISC PRO','https://i.ytimg.com/vi/017K5zu2KLg/hqdefault.jpg','017K5zu2KLg.mp3',NULL,5753805,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('21e896fc-91dc-4dbd-8416-23c4da211fbf','https://www.youtube.com/watch?v=0Qr7sP7G5RQ','youtube','0Qr7sP7G5RQ','Marwa Loud, @MohaK - Ghir Ntiya (Clip Officiel)','Marwa Loud','https://i.ytimg.com/vi/0Qr7sP7G5RQ/hqdefault.jpg','0Qr7sP7G5RQ.mp3',NULL,6671781,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('978bb45d-d12a-4cb3-9515-249f4890910c','https://www.youtube.com/watch?v=0TFNGRYMz1U','youtube','0TFNGRYMz1U','ZAZ - Je veux (Clip officiel)','Zaz Official','https://i.ytimg.com/vi/0TFNGRYMz1U/hqdefault.jpg','0TFNGRYMz1U.mp3',NULL,7476981,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('8c315a7f-701a-43eb-b374-454f080d6aee','https://www.youtube.com/watch?v=0VP4u_eBj4A','youtube','0VP4u_eBj4A','EL DEY Maria Clip Officiel','ASWATT STUDIO','https://i.ytimg.com/vi/0VP4u_eBj4A/hqdefault.jpg','0VP4u_eBj4A.mp3',NULL,8237565,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('1261d5c8-83a9-41df-9c17-d4c59bdc1080','https://www.youtube.com/watch?v=1Z82k1MkIBQ','youtube','1Z82k1MkIBQ','Flenn - Liyam [ Bande Originale ]','Flenn','https://i.ytimg.com/vi/1Z82k1MkIBQ/hqdefault.jpg','1Z82k1MkIBQ.mp3',NULL,6523773,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('d5296126-f196-4de7-9c4f-5d92818233bd','https://www.youtube.com/watch?v=3RuHe_eWOt0','youtube','3RuHe_eWOt0','Samara - Minimum (Official Music Video)','Samara','https://i.ytimg.com/vi/3RuHe_eWOt0/hqdefault.jpg','3RuHe_eWOt0.mp3',NULL,6437613,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('c8bf2e97-a88d-4e3d-a7f6-f9dd83aa92cf','https://www.youtube.com/watch?v=5AzBdkbI0OY','youtube','5AzBdkbI0OY','سألتك حبيبي - فيروز | Saaltak Habiby - Fairuz','Fairuzyat - فيروزيات','https://i.ytimg.com/vi/5AzBdkbI0OY/hqdefault.jpg','5AzBdkbI0OY.mp3',NULL,11111397,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('0997f017-cca0-4c89-b946-067b3b64c294','https://www.youtube.com/watch?v=8CnpqLtzqQY','youtube','8CnpqLtzqQY','Sherine - Sabry Aalil (Music Video) | (شيرين - صبري قليل (فيديو كليب','Free Music "Nasr Mahrous"','https://i.ytimg.com/vi/8CnpqLtzqQY/hqdefault.jpg','8CnpqLtzqQY.mp3',NULL,5578341,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('d6b41c88-3c13-413a-8d28-a64d5c6cb8c3','https://www.youtube.com/watch?v=9LOZwti7tc8','youtube','9LOZwti7tc8','Mohamed Djeffal 2025 - Ghaddara غدارة - (Live Mariage)','Mohamed Djeffal - محمد جفال','https://i.ytimg.com/vi/9LOZwti7tc8/hqdefault.jpg','9LOZwti7tc8.mp3',NULL,4972269,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('b0a5baef-6604-429c-8dc7-24eb51136647','https://www.youtube.com/watch?v=D0kxH1xGUxw','youtube','D0kxH1xGUxw','Bibi Maestro ft. Cheb Zoubir - Zine Chaouia Yhabel⎟زين الشاوية يهبل','BiBi MAESTRO','https://i.ytimg.com/vi/D0kxH1xGUxw/hqdefault.jpg','D0kxH1xGUxw.mp3',NULL,11518509,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('a5e15c2f-e2e7-4e61-8213-56632dd17012','https://www.youtube.com/watch?v=DF3XjEhJ40Y','youtube','DF3XjEhJ40Y','Indila - Love Story (Official Music Video)','IndilaVEVO','https://i.ytimg.com/vi/DF3XjEhJ40Y/hqdefault.jpg','DF3XjEhJ40Y.mp3',NULL,8986125,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('4b746a08-26cf-4089-85ff-76a83a50638c','https://www.youtube.com/watch?v=DqUd72pK15Y','youtube','DqUd72pK15Y','Omah Lay - Godly [Official Music Video]','Omah Lay','https://i.ytimg.com/vi/DqUd72pK15Y/hqdefault.jpg','DqUd72pK15Y.mp3',NULL,5589357,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('2639613e-9e00-4a85-b386-4c37ace1e08e','https://www.youtube.com/watch?v=F_rEHfLgdcY','youtube','F_rEHfLgdcY','GIMS - J''me tire (Clip officiel)','MaitreGimsVEVO','https://i.ytimg.com/vi/F_rEHfLgdcY/hqdefault.jpg','F_rEHfLgdcY.mp3',NULL,8095341,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('4384d3d3-0c6d-4e4f-988e-5c3a7506780c','https://www.youtube.com/watch?v=K5KAc5CoCuk','youtube','K5KAc5CoCuk','Indila - Dernière Danse (Clip Officiel)','IndilaVEVO','https://i.ytimg.com/vi/K5KAc5CoCuk/hqdefault.jpg','K5KAc5CoCuk.mp3',NULL,6479133,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('bce30acb-35d2-4743-8efd-a6fb464a346f','https://www.youtube.com/watch?v=Si9kWKnJKxE','youtube','Si9kWKnJKxE','LAZARO - ZOMBIE (Official Music Video)','LAZARO','https://i.ytimg.com/vi/Si9kWKnJKxE/hqdefault.jpg','Si9kWKnJKxE.mp3',NULL,6093237,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('8fa27c64-1b64-4045-960d-38ee623261b5','https://www.youtube.com/watch?v=Slj07rEgBIE','youtube','Slj07rEgBIE','عيسى الجرموني شاوي حر قديم متبكيش ياجميلة aissa El djermouni','Neghma TV','https://i.ytimg.com/vi/Slj07rEgBIE/hqdefault.jpg','Slj07rEgBIE.mp3',NULL,6881517,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('b8b29efa-2a6e-4e5d-85b0-2c416c546644','https://www.youtube.com/watch?v=UKrpJvoJlUg','youtube','UKrpJvoJlUg','Cheb Khaled - Detni Essekra ( Datni Sekra ) * Lyrics *','Sofien Nahdi','https://i.ytimg.com/vi/UKrpJvoJlUg/hqdefault.jpg','UKrpJvoJlUg.mp3',NULL,8950245,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('c0d0f3dd-8604-44df-8c40-4c0b1d8875f7','https://www.youtube.com/watch?v=VhyvGwxcfTc','youtube','VhyvGwxcfTc','Mounim Slimani - Jedi ou Jedek (Official Lyric Video, 2025) | منعم سليماني - جدي وجدك','Mounim Slimani','https://i.ytimg.com/vi/VhyvGwxcfTc/hqdefault.jpg','VhyvGwxcfTc.mp3',NULL,6120237,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('b4d37006-5dd3-400a-b78d-450e32495a2f','https://www.youtube.com/watch?v=WDOpAb-YiaY','youtube','WDOpAb-YiaY','Ser El Primero (Bachata Remix)','SoyCanallita - Topic','https://i.ytimg.com/vi/WDOpAb-YiaY/hqdefault.jpg','WDOpAb-YiaY.mp3',NULL,6826173,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('d208cf1d-7d90-4047-9c8e-e4fbc7a676b3','https://www.youtube.com/watch?v=YBETWFkzTtM','youtube','YBETWFkzTtM','Bilel Tacchini - choufou l’amour madar fiya (Official cover Amine Babylone Live 2023)','Bilel tacchini / بلال طاكيني','https://i.ytimg.com/vi/YBETWFkzTtM/hqdefault.jpg','YBETWFkzTtM.mp3',NULL,5836581,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('12dd78d1-407a-48b3-9203-5f9e2b2ed684','https://www.youtube.com/watch?v=YLIWleB0g78','youtube','YLIWleB0g78','[EXCLU] Soolking "Guérilla" #PlanèteRap','SkyrockFM','https://i.ytimg.com/vi/YLIWleB0g78/hqdefault.jpg','YLIWleB0g78.mp3',NULL,7210701,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('a9aaa523-00b4-4536-8766-464c3b0c3206','https://www.youtube.com/watch?v=ZjrZWIISlY8','youtube','ZjrZWIISlY8','Samara - Souk (Official Music Video)','Samara','https://i.ytimg.com/vi/ZjrZWIISlY8/hqdefault.jpg','ZjrZWIISlY8.mp3',NULL,7120461,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('39107ac1-d184-4a3d-bc08-1264be53355a','https://www.youtube.com/watch?v=_6aNzO5gH7g','youtube','_6aNzO5gH7g','Mourad Guerbas "TASEDA-INU" clip officiel 2023 4K','Mourad Guerbas','https://i.ytimg.com/vi/_6aNzO5gH7g/hqdefault.jpg','_6aNzO5gH7g.mp3',NULL,9678141,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('e215a201-b7d8-4e5f-ba49-acac3a5e28b0','https://www.youtube.com/watch?v=bo7-371uZlE','youtube','bo7-371uZlE','المرحوم شاب كاتشو . سوسم سوسم امتوسة .   cheb katcou sousem sousem  amtousa','MOURAD CHAOUI','https://i.ytimg.com/vi/bo7-371uZlE/hqdefault.jpg','bo7-371uZlE.mp3',NULL,3719733,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('d06e5cc3-9092-46db-8efe-9ca3a0bdd9ba','https://www.youtube.com/watch?v=bsPWx59yvYI','youtube','bsPWx59yvYI','Soolking - Dalida [Clip Officiel] Prod by Diias','Soolking Officiel','https://i.ytimg.com/vi/bsPWx59yvYI/hqdefault.jpg','bsPWx59yvYI.mp3',NULL,9508773,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('d82499ed-9c28-48e4-898f-2ee7d3580dce','https://www.youtube.com/watch?v=c5y7USxRdO8','youtube','c5y7USxRdO8','( اغنية يا رايح وين مسافر )  Ay-Men production','AyMen - أيمن','https://i.ytimg.com/vi/c5y7USxRdO8/hqdefault.jpg','c5y7USxRdO8.mp3',NULL,7168749,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('75158385-302b-4f33-b462-0a64a045d7ed','https://www.youtube.com/watch?v=cwgtjcY5ToY','youtube','cwgtjcY5ToY','ZADK - D.M.T [ clip officielle ]','ŘÂP ĎŽ','https://i.ytimg.com/vi/cwgtjcY5ToY/hqdefault.jpg','cwgtjcY5ToY.mp3',NULL,8735565,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('c2dd0ecb-1dc6-416d-9a97-94ba2347f4c9','https://www.youtube.com/watch?v=es9kH_pnnHk','youtube','es9kH_pnnHk','Flenn - 4 Chiffres','Flenn','https://i.ytimg.com/vi/es9kH_pnnHk/hqdefault.jpg','es9kH_pnnHk.mp3',NULL,5317581,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('887e9eb9-25cd-4049-8d38-25fd93a7d743','https://www.youtube.com/watch?v=fqh-tEoorqo','youtube','fqh-tEoorqo','Cheba Warda 2023 FT Manini Solazur | Galbi khasah molah © L3achk kamalt m3ah |  Exclusive Music Live','Møhamed Dîb /محمد ديب','https://i.ytimg.com/vi/fqh-tEoorqo/hqdefault.jpg','fqh-tEoorqo.mp3',NULL,7873485,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('0ffc9793-b93b-4e9f-8462-f3125c0e48da','https://www.youtube.com/watch?v=iBCJSDkJxmk','youtube','iBCJSDkJxmk','МЗА LECHRANE (Red Tape Version)','RED TAPE ','https://i.ytimg.com/vi/iBCJSDkJxmk/hqdefault.jpg','iBCJSDkJxmk.mp3',NULL,6968901,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('3ffca553-b173-4612-b3ee-8f0c97d9f255','https://www.youtube.com/watch?v=jbR7YDdeMfY','youtube','jbR7YDdeMfY','SHERINE X HOUARI DAUPHIN - GALBI (ALI S REMIX)','Ali S Music','https://i.ytimg.com/vi/jbR7YDdeMfY/hqdefault.jpg','jbR7YDdeMfY.mp3',NULL,4998453,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('9880bb1a-b03b-4ac9-9ad6-fdd4b18ec8fc','https://www.youtube.com/watch?v=kK23SVUrojc','youtube','kK23SVUrojc','Djo: bachtola - les berberes 1989','BLACK HOLE','https://i.ytimg.com/vi/kK23SVUrojc/hqdefault.jpg','kK23SVUrojc.mp3',NULL,6588285,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('e3f7d316-d54c-421f-93f3-f5dd53b173e2','https://www.youtube.com/watch?v=mryhQ4U0rP4','youtube','mryhQ4U0rP4','فايق يا هوى - فيروز | Fayek Ya Hawa - Fairuz','Fairuzyat - فيروزيات','https://i.ytimg.com/vi/mryhQ4U0rP4/hqdefault.jpg','mryhQ4U0rP4.mp3',NULL,12957069,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('d8aa85f9-bb91-48bd-9e16-1057944fd2c1','https://www.youtube.com/watch?v=qj6qtnzas6w','youtube','qj6qtnzas6w','اغنيه دايا دايا - daya daya - جينا سامي','Milad & Jena ','https://i.ytimg.com/vi/qj6qtnzas6w/hqdefault.jpg','qj6qtnzas6w.mp3',NULL,1891917,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('ab1769da-3ffe-4dd4-ba3b-7455c1ff6319','https://www.youtube.com/watch?v=sM1UKzU3uEs','youtube','sM1UKzU3uEs','Mohamed Djeffal 2025 - Dirili Lavocat  ديريلي لافوكات - ( Live Mariage )','Mohamed Djeffal - محمد جفال','https://i.ytimg.com/vi/sM1UKzU3uEs/hqdefault.jpg','sM1UKzU3uEs.mp3',NULL,8482293,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('bdf95408-41e4-45b3-8631-9d1274a623cc','https://www.youtube.com/watch?v=tKpHdhFxICg','youtube','tKpHdhFxICg','Warda - batwanis Beek | وردة - بتونس بيك','Abdullah Mughram','https://i.ytimg.com/vi/tKpHdhFxICg/hqdefault.jpg','tKpHdhFxICg.mp3',NULL,21273549,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('d6b945cc-7b49-4776-9aec-18a664513355','https://www.youtube.com/watch?v=taeehJ6Fc30','youtube','taeehJ6Fc30','Soolking - Koula Youm #PlanèteRap','SkyrockFM','https://i.ytimg.com/vi/taeehJ6Fc30/hqdefault.jpg','taeehJ6Fc30.mp3',NULL,5911893,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('4f1739ed-604b-4a62-8cd2-1116433f7d1b','https://www.youtube.com/watch?v=tfXpR6MZNuk','youtube','tfXpR6MZNuk','Black Morte ( ghazzal reem 🦌 غزال الريم ) بلاك مورتي ','Black Morte','https://i.ytimg.com/vi/tfXpR6MZNuk/hqdefault.jpg','tfXpR6MZNuk.mp3',NULL,6867261,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('2a5e057d-9247-40fb-8594-525517eb63c6','https://www.youtube.com/watch?v=uKw_tiDshlI','youtube','uKw_tiDshlI','Mc Artisan - ELGHIRA Ft Didine Canon 16   (Prod. By Zmajor)','Mc Artisan','https://i.ytimg.com/vi/uKw_tiDshlI/hqdefault.jpg','uKw_tiDshlI.mp3',NULL,5360349,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('af59ef4e-26ce-456a-9230-7127caa8d1df','https://www.youtube.com/watch?v=22lBZpuyZxA','youtube','22lBZpuyZxA','Balti - Allo (Official Music Video)','Thisiz Balti','https://i.ytimg.com/vi/22lBZpuyZxA/hqdefault.jpg','youtube-22lBZpuyZxA.mp3',NULL,8022069,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('93c46a0f-01e6-4d8b-b931-18964443b53d','https://www.youtube.com/watch?v=6POZlJAZsok','youtube','6POZlJAZsok','Just the Two of Us (feat. Bill Withers)','Grover Washington, Jr. - Topic','https://i.ytimg.com/vi/6POZlJAZsok/hqdefault.jpg','youtube-6POZlJAZsok.mp3',NULL,14682093,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('8d028369-40dc-40e9-a878-c1d1f31f3334','https://www.youtube.com/watch?v=6VyC2bkxahI','youtube','6VyC2bkxahI','فهد بلان - واشرح لها عن حلاتي..','Samir Sous','https://i.ytimg.com/vi/6VyC2bkxahI/hqdefault.jpg','youtube-6VyC2bkxahI.mp3',NULL,11894781,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('0980ed45-9d1c-42f0-855d-23b27fb9713e','https://www.youtube.com/watch?v=G7KNmW9a75Y','youtube','G7KNmW9a75Y','Miley Cyrus - Flowers (Official Video)','MileyCyrusVEVO','https://i.ytimg.com/vi/G7KNmW9a75Y/hqdefault.jpg','youtube-G7KNmW9a75Y.mp3',NULL,6580173,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('eb502e2d-f9e6-4782-958b-e3480d225f3a','https://www.youtube.com/watch?v=MxjrsDV8Aeo','youtube','MxjrsDV8Aeo','CKay - Love Nwantiti (ft. ElGrandeToto) [North African Remix] [Official Music Video]','CKay','https://i.ytimg.com/vi/MxjrsDV8Aeo/hqdefault.jpg','youtube-MxjrsDV8Aeo.mp3',NULL,4727421,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('5dd206de-e3ce-4d88-a67e-b53d4e1aabe7','https://www.youtube.com/watch?v=QJO3ROT-A4E','youtube','QJO3ROT-A4E','One Direction - What Makes You Beautiful (Official Video)','OneDirectionVEVO','https://i.ytimg.com/vi/QJO3ROT-A4E/hqdefault.jpg','youtube-QJO3ROT-A4E.mp3',NULL,6647373,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('1acaa3ef-8741-4a72-b51c-4936c3cad464','https://www.youtube.com/watch?v=Uk0a77THvoE','youtube','Uk0a77THvoE','Nancy Ajram - Aala Shanak (Official Lyric Video) / نانسي عجرم - على شانك (حبك سفاح)','Nancy Ajram','https://i.ytimg.com/vi/Uk0a77THvoE/hqdefault.jpg','youtube-Uk0a77THvoE.mp3',NULL,6554637,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('7b567c7a-5a6a-48b4-8c17-b8bb6a573893','https://www.youtube.com/watch?v=hTWKbfoikeg','youtube','hTWKbfoikeg','Nirvana - Smells Like Teen Spirit (Official Music Video)','NirvanaVEVO','https://i.ytimg.com/vi/hTWKbfoikeg/hqdefault.jpg','youtube-hTWKbfoikeg.mp3',NULL,9401373,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('9de6c9d1-c1b5-4e0a-82e2-30b43008d802','https://www.youtube.com/watch?v=j5-yKhDd64s','youtube','j5-yKhDd64s','Eminem - Not Afraid','EminemVEVO','https://i.ytimg.com/vi/j5-yKhDd64s/hqdefault.jpg','youtube-j5-yKhDd64s.mp3',NULL,7691709,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('b589579b-e1f2-489b-84b4-80bd85e9d1fc','https://www.youtube.com/watch?v=yUqtmrhyvtM','youtube','yUqtmrhyvtM','La mass le vrai - Tafi (Official Music Video) | طافي @justmedbeats. prod','La mass le vrai ','https://i.ytimg.com/vi/yUqtmrhyvtM/hqdefault.jpg','youtube-yUqtmrhyvtM.mp3',NULL,7918077,NULL,datetime('now'));
INSERT OR IGNORE INTO tracks (id,original_url,extractor,extractor_id,title,artist,thumbnail_url,storage_path,duration_sec,file_size,owner_id,created_at) VALUES ('11beef89-74f8-4fec-b3ab-0936dd81e16f','https://www.youtube.com/watch?v=zKGW9V1WSl8','youtube','zKGW9V1WSl8','Babylone - Zina (Official Music Video) | بابيلون - زينة','ASWATT STUDIO','https://i.ytimg.com/vi/zKGW9V1WSl8/hqdefault.jpg','zKGW9V1WSl8.mp3',NULL,7451781,NULL,datetime('now'));
